version: '3.9'

services: 
  db:
    container_name: postgres_test_db
    image: postgres:14.2-alpine
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:z
  db_admin:
    container_name: postgres_test_db_admin
    image: dpage/pgadmin4:6.7
    env_file: '.env'
    ports:
      - "9090:80"
    volumes:
      - ./pgadmin/pgadmin4/servers.json:/pgadmin4/servers.json:z
    #logging:
      #driver: none
    depends_on: 
      - db